# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_registrar_accesorios.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(772, 541)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 174);")
        self.centalwidget = QtWidgets.QWidget(MainWindow)
        self.centalwidget.setObjectName("centalwidget")
        self.label_accesorios = QtWidgets.QLabel(self.centalwidget)
        self.label_accesorios.setGeometry(QtCore.QRect(240, 110, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_accesorios.setFont(font)
        self.label_accesorios.setObjectName("label_accesorios")
        self.label_2 = QtWidgets.QLabel(self.centalwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 190, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centalwidget)
        self.label.setGeometry(QtCore.QRect(250, 230, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.entrada_mascota_accesorios = QtWidgets.QLineEdit(self.centalwidget)
        self.entrada_mascota_accesorios.setGeometry(QtCore.QRect(370, 190, 113, 20))
        self.entrada_mascota_accesorios.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrada_mascota_accesorios.setObjectName("entrada_mascota_accesorios")
        self.entrada_accesorios = QtWidgets.QLineEdit(self.centalwidget)
        self.entrada_accesorios.setGeometry(QtCore.QRect(370, 230, 113, 20))
        self.entrada_accesorios.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrada_accesorios.setObjectName("entrada_accesorios")
        self.label_4 = QtWidgets.QLabel(self.centalwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 270, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.entrada_talla_accesorios = QtWidgets.QLineEdit(self.centalwidget)
        self.entrada_talla_accesorios.setGeometry(QtCore.QRect(370, 270, 113, 20))
        self.entrada_talla_accesorios.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrada_talla_accesorios.setObjectName("entrada_talla_accesorios")
        self.label_5 = QtWidgets.QLabel(self.centalwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 310, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.entrada_tipo_accesorios = QtWidgets.QLineEdit(self.centalwidget)
        self.entrada_tipo_accesorios.setGeometry(QtCore.QRect(370, 310, 113, 20))
        self.entrada_tipo_accesorios.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrada_tipo_accesorios.setObjectName("entrada_tipo_accesorios")
        self.label_6 = QtWidgets.QLabel(self.centalwidget)
        self.label_6.setGeometry(QtCore.QRect(250, 350, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.entrada_precio_accesorios = QtWidgets.QLineEdit(self.centalwidget)
        self.entrada_precio_accesorios.setGeometry(QtCore.QRect(370, 350, 113, 20))
        self.entrada_precio_accesorios.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrada_precio_accesorios.setObjectName("entrada_precio_accesorios")
        self.boton_registrar_accesorios = QtWidgets.QPushButton(self.centalwidget)
        self.boton_registrar_accesorios.setGeometry(QtCore.QRect(284, 440, 221, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.boton_registrar_accesorios.setFont(font)
        self.boton_registrar_accesorios.setStyleSheet("background-color: rgb(255, 216, 171);")
        self.boton_registrar_accesorios.setObjectName("boton_registrar_accesorios")
        MainWindow.setCentralWidget(self.centalwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_accesorios.setText(_translate("MainWindow", "INTRODUCE EL TIPO DE ACCESORIO"))
        self.label_2.setText(_translate("MainWindow", "MASCOTA"))
        self.label.setText(_translate("MainWindow", "ACCESORIO"))
        self.label_4.setText(_translate("MainWindow", "TALLA"))
        self.label_5.setText(_translate("MainWindow", "TIPO"))
        self.label_6.setText(_translate("MainWindow", "PRECIO"))
        self.boton_registrar_accesorios.setText(_translate("MainWindow", "REGISTRAR"))

