# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_table_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(158, 200, 172);\n"
"background-color: rgb(195, 172, 200);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 100, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabla_accesorios = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_accesorios.setGeometry(QtCore.QRect(110, 180, 601, 401))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabla_accesorios.setFont(font)
        self.tabla_accesorios.setStyleSheet("background-color: rgb(188, 200, 185);\n"
"background-color: rgb(255, 255, 255);")
        self.tabla_accesorios.setObjectName("tabla_accesorios")
        self.tabla_accesorios.setColumnCount(6)
        self.tabla_accesorios.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_accesorios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_accesorios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_accesorios.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_accesorios.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_accesorios.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_accesorios.setHorizontalHeaderItem(5, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LISTADO TABLE WIDGET"))
        item = self.tabla_accesorios.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "mascota"))
        item = self.tabla_accesorios.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "accesorio"))
        item = self.tabla_accesorios.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "talla"))
        item = self.tabla_accesorios.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "tipo"))
        item = self.tabla_accesorios.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "precio"))
        item = self.tabla_accesorios.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "borrar"))

