# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_table_widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(158, 200, 172);\n"
"background-color: rgb(195, 172, 200);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 100, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabla_accesorios = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla_accesorios.setGeometry(QtCore.QRect(10, 160, 761, 401))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabla_accesorios.setFont(font)
        self.tabla_accesorios.setStyleSheet("background-color: rgb(188, 200, 185);\n"
"background-color: rgb(255, 255, 255);")
        self.tabla_accesorios.setObjectName("tabla_accesorios")
        self.tabla_accesorios.setColumnCount(9)
        self.tabla_accesorios.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_accesorios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_accesorios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_accesorios.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_accesorios.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_accesorios.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_accesorios.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_accesorios.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_accesorios.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_accesorios.setHorizontalHeaderItem(8, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LISTADO TABLE WIDGET"))
        item = self.tabla_accesorios.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tabla_accesorios.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "mascota"))
        item = self.tabla_accesorios.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "accesorios"))
        item = self.tabla_accesorios.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "tipo"))
        item = self.tabla_accesorios.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ver detalles"))
        item = self.tabla_accesorios.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "borrar"))
        item = self.tabla_accesorios.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "editar"))
        item = self.tabla_accesorios.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "imagen"))
        item = self.tabla_accesorios.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Column"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
