# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_editar_accesorio.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 541)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 174);\n"
"background-color: rgb(255, 170, 255);")
        self.centalwidget = QtWidgets.QWidget(MainWindow)
        self.centalwidget.setObjectName("centalwidget")
        self.label_accesorios = QtWidgets.QLabel(self.centalwidget)
        self.label_accesorios.setGeometry(QtCore.QRect(290, 40, 361, 31))
        font = QtGui.QFont()
        font.setFamily("Aharoni")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_accesorios.setFont(font)
        self.label_accesorios.setObjectName("label_accesorios")
        self.label_2 = QtWidgets.QLabel(self.centalwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 100, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centalwidget)
        self.label.setGeometry(QtCore.QRect(80, 140, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.entrada_mascota_accesorio = QtWidgets.QLineEdit(self.centalwidget)
        self.entrada_mascota_accesorio.setGeometry(QtCore.QRect(200, 100, 113, 20))
        self.entrada_mascota_accesorio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrada_mascota_accesorio.setObjectName("entrada_mascota_accesorio")
        self.entrada_accesorios = QtWidgets.QLineEdit(self.centalwidget)
        self.entrada_accesorios.setGeometry(QtCore.QRect(200, 140, 113, 20))
        self.entrada_accesorios.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrada_accesorios.setObjectName("entrada_accesorios")
        self.label_4 = QtWidgets.QLabel(self.centalwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 180, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.entrada_talla_accesorio = QtWidgets.QLineEdit(self.centalwidget)
        self.entrada_talla_accesorio.setGeometry(QtCore.QRect(200, 180, 113, 20))
        self.entrada_talla_accesorio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrada_talla_accesorio.setObjectName("entrada_talla_accesorio")
        self.label_5 = QtWidgets.QLabel(self.centalwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 210, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.entrada_tipo_accesorio = QtWidgets.QLineEdit(self.centalwidget)
        self.entrada_tipo_accesorio.setGeometry(QtCore.QRect(200, 210, 113, 20))
        self.entrada_tipo_accesorio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrada_tipo_accesorio.setObjectName("entrada_tipo_accesorio")
        self.label_6 = QtWidgets.QLabel(self.centalwidget)
        self.label_6.setGeometry(QtCore.QRect(110, 250, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.entrada_precio_accesorio = QtWidgets.QLineEdit(self.centalwidget)
        self.entrada_precio_accesorio.setGeometry(QtCore.QRect(200, 250, 113, 20))
        self.entrada_precio_accesorio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrada_precio_accesorio.setObjectName("entrada_precio_accesorio")
        self.boton_guardar_cambios_accesorio = QtWidgets.QPushButton(self.centalwidget)
        self.boton_guardar_cambios_accesorio.setGeometry(QtCore.QRect(270, 470, 221, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.boton_guardar_cambios_accesorio.setFont(font)
        self.boton_guardar_cambios_accesorio.setStyleSheet("background-color: rgb(255, 216, 171);\n"
"background-color: rgb(245,242,255);")
        self.boton_guardar_cambios_accesorio.setObjectName("boton_guardar_cambios_accesorio")
        self.checkbox_ofertas = QtWidgets.QCheckBox(self.centalwidget)
        self.checkbox_ofertas.setGeometry(QtCore.QRect(240, 300, 271, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.checkbox_ofertas.setFont(font)
        self.checkbox_ofertas.setObjectName("checkbox_ofertas")
        self.combo_cliente = QtWidgets.QComboBox(self.centalwidget)
        self.combo_cliente.setGeometry(QtCore.QRect(320, 350, 61, 22))
        self.combo_cliente.setStyleSheet("background-color: rgb(255, 255, 247);")
        self.combo_cliente.setEditable(False)
        self.combo_cliente.setObjectName("combo_cliente")
        self.combo_cliente.addItem("")
        self.combo_cliente.addItem("")
        self.label_7 = QtWidgets.QLabel(self.centalwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 350, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.radio_standar = QtWidgets.QRadioButton(self.centalwidget)
        self.radio_standar.setGeometry(QtCore.QRect(520, 360, 82, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radio_standar.setFont(font)
        self.radio_standar.setChecked(True)
        self.radio_standar.setObjectName("radio_standar")
        self.label_8 = QtWidgets.QLabel(self.centalwidget)
        self.label_8.setGeometry(QtCore.QRect(300, 390, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.radio_urgente = QtWidgets.QRadioButton(self.centalwidget)
        self.radio_urgente.setGeometry(QtCore.QRect(520, 390, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radio_urgente.setFont(font)
        self.radio_urgente.setObjectName("radio_urgente")
        self.radio_recogida = QtWidgets.QRadioButton(self.centalwidget)
        self.radio_recogida.setGeometry(QtCore.QRect(520, 420, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radio_recogida.setFont(font)
        self.radio_recogida.setObjectName("radio_recogida")
        self.label_9 = QtWidgets.QLabel(self.centalwidget)
        self.label_9.setGeometry(QtCore.QRect(560, 90, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.boton_seleccionar_archivo = QtWidgets.QPushButton(self.centalwidget)
        self.boton_seleccionar_archivo.setGeometry(QtCore.QRect(530, 130, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.boton_seleccionar_archivo.setFont(font)
        self.boton_seleccionar_archivo.setStyleSheet("background-color: rgb(245, 242, 255);")
        self.boton_seleccionar_archivo.setObjectName("boton_seleccionar_archivo")
        self.label_imagen = QtWidgets.QLabel(self.centalwidget)
        self.label_imagen.setGeometry(QtCore.QRect(490, 200, 241, 161))
        self.label_imagen.setText("")
        self.label_imagen.setObjectName("label_imagen")
        self.label_error_mascota = QtWidgets.QLabel(self.centalwidget)
        self.label_error_mascota.setGeometry(QtCore.QRect(340, 100, 131, 20))
        self.label_error_mascota.setObjectName("label_error_mascota")
        self.label_error_accesorio = QtWidgets.QLabel(self.centalwidget)
        self.label_error_accesorio.setGeometry(QtCore.QRect(340, 140, 141, 20))
        self.label_error_accesorio.setObjectName("label_error_accesorio")
        MainWindow.setCentralWidget(self.centalwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_accesorios.setText(_translate("MainWindow", "MODIFICA TU PEDIDO"))
        self.label_2.setText(_translate("MainWindow", "MASCOTA"))
        self.label.setText(_translate("MainWindow", "ACCESORIO"))
        self.label_4.setText(_translate("MainWindow", "TALLA"))
        self.label_5.setText(_translate("MainWindow", "TIPO"))
        self.label_6.setText(_translate("MainWindow", "PRECIO"))
        self.boton_guardar_cambios_accesorio.setText(_translate("MainWindow", "GUARDAR CAMBIOS"))
        self.checkbox_ofertas.setText(_translate("MainWindow", "Recibir ofertas por mail"))
        self.combo_cliente.setItemText(0, _translate("MainWindow", "si"))
        self.combo_cliente.setItemText(1, _translate("MainWindow", "no"))
        self.label_7.setText(_translate("MainWindow", "¿Ya eres cliente?"))
        self.radio_standar.setText(_translate("MainWindow", "Standar"))
        self.label_8.setText(_translate("MainWindow", "Tipo de envío "))
        self.radio_urgente.setText(_translate("MainWindow", "Urgente"))
        self.radio_recogida.setText(_translate("MainWindow", "Recogida"))
        self.label_9.setText(_translate("MainWindow", "Selecciona :"))
        self.boton_seleccionar_archivo.setText(_translate("MainWindow", "TIPO DE MASCOTA"))
        self.label_error_mascota.setText(_translate("MainWindow", "ERROR MASCOTA"))
        self.label_error_accesorio.setText(_translate("MainWindow", "ERROR ACCESORIO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
